### PR TITLE
Update data.json

### PR DESCRIPTION
**Pull request by xavierlacot**
Added JoliCode's "Badass pageflow" widget

### CODE REVIEW

**Comment by xavierlacot** [comment]
Hi Josh, any news on this PR please? :-)

**Comment by ternel** [comment]
Ping @joshjensen :)

**Comment by joshjensen** [comment]
Sorry guys! I have been out of town. Merging now.

**Comment by joshjensen** [comment]
Thanks for the PR guys. It is all merged in and the site has been updated.

http://alloylove.com/#Badass

**Pull request merged**
